(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"YM",
  Authors -> {"Raj Patil"},
  Emails -> {"raj.patil.physics@gmail.com"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "c",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 }
}


(*        Definitions       *)

FAGaugeXi[ U[1] ] = 1;



TheLabel[ V[1, {__}] ] := TheLabel[V[1]];
TheLabel[ U[1, {__}] ] := TheLabel[U[1]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[1, {e1x2}] , V[1, {e2x2}] ] == {{0, (-I)*(-1 + ZG)*IndexDelta[e1x2, e2x2]}, {0, I*(-1 + ZG)*IndexDelta[e1x2, e2x2]}},

C[ -U[1, {e1x1}] , U[1, {e2x1}] ] == {{0, I*(-1 + Zc)*IndexDelta[e1x1, e2x1]}, {0, 0}},

C[ -U[1, {e1x1}] , U[1, {e2x1}] , V[1, {e3x2}] ] == {{g*FASUNF[e3x2, e1x1, e2x1], g*(-1 + Zc*Sqrt[ZG]*ZGcc)*FASUNF[e3x2, e1x1, e2x1]}, {g*FASUNF[e3x2, e1x1, e2x1], g*(-1 + Zc*Sqrt[ZG]*ZGcc)*FASUNF[e3x2, e1x1, e2x1]}, {0, 0}},

C[ V[1, {e1x2}] , V[1, {e2x2}] , V[1, {e3x2}] ] == {{g*FASUNF[e1x2, e2x2, e3x2], g*(-1 + ZG^(3/2)*ZG3)*FASUNF[e1x2, e2x2, e3x2]}, {-(g*FASUNF[e1x2, e2x2, e3x2]), -(g*(-1 + ZG^(3/2)*ZG3)*FASUNF[e1x2, e2x2, e3x2])}, {-(g*FASUNF[e1x2, e2x2, e3x2]), -(g*(-1 + ZG^(3/2)*ZG3)*FASUNF[e1x2, e2x2, e3x2])}, {g*FASUNF[e1x2, e2x2, e3x2], g*(-1 + ZG^(3/2)*ZG3)*FASUNF[e1x2, e2x2, e3x2]}, {g*FASUNF[e1x2, e2x2, e3x2], g*(-1 + ZG^(3/2)*ZG3)*FASUNF[e1x2, e2x2, e3x2]}, {-(g*FASUNF[e1x2, e2x2, e3x2]), -(g*(-1 + ZG^(3/2)*ZG3)*FASUNF[e1x2, e2x2, e3x2])}},

C[ V[1, {e1x2}] , V[1, {e2x2}] , V[1, {e3x2}] , V[1, {e4x2}] ] == {{I*g^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), I*g^2*(-1 + ZG^2*ZG4)*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2])}, {(-I)*g^2*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), (-I)*g^2*(-1 + ZG^2*ZG4)*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2])}, {(-I)*g^2*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), (-I)*g^2*(-1 + ZG^2*ZG4)*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2])}}

}

