(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"LSM",
  Authors -> {"Raj Patil"},
  Emails -> {"raj.patil.physics@gmail.com"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={S[2]};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> Straight,
    PropagatorArrow -> None,
    Mass -> mH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "b",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mb,
    Indices -> {} }
}


(*        Definitions       *)

FAGaugeXi[ S[1] ] = 1;
FAGaugeXi[ S[2] ] = 1;

mH[ ___ ] := mH;
mb[ ___ ] := mb;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{((-3*I)/2)*g4, ((-3*I)/2)*g4*(-1 + Zb^2*Zbbbb)}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-1/2*I)*g4, (-1/2*I)*g4*(-1 + Zb*ZbbHH*ZH)}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{((-3*I)/2)*g4, ((-3*I)/2)*g4*(-1 + ZH^2*ZHHHH)}},

C[ S[2] , S[2] , S[1] ] == {{(-1/2*I)*g4*vev, (-1/2*I)*g4*vev*(-1 + Zb*ZbbH*Sqrt[ZH]*Zv)}},

C[ S[1] , S[1] , S[1] ] == {{((-3*I)/2)*g4*vev, ((-3*I)/2)*g4*vev*(-1 + ZH^(3/2)*ZHHH*Zv)}},

C[ S[1] , S[1] ] == {{0, (-1/4*I)*g4*vev^2*(-2 - ZH + ZH*Zv^2 + 2*ZH*ZmH^2*Zv^2)}, {0, (-I)*(-1 + ZH)}},

C[ S[2] , S[2] ] == {{0, (-1/4*I)*g4*vev^2*Zb*(-1 + Zv)*(1 + Zv)}, {0, (-I)*(-1 + Zb)}},

C[ S[1] ] == {{0, (-1/4*I)*g4*vev^3*Sqrt[ZH]*(-1 + Zv)*Zv*(1 + Zv)}}

}

M$IntParams = {mb -> 0, mH -> (Sqrt[g4]*vev)/Sqrt[2]} ;
