(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"QED",
  Authors -> {"Raj Patil"},
  Emails -> {"raj.patil.physics@gmail.com"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

F[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {-Q},
    PropagatorLabel -> "\[Psi]",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> mP,
    Indices -> {} }
}


(*        Definitions       *)


mP[ ___ ] := mP;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ V[1] , V[1] ] == {{0, (-I)*(-1 + ZA)}, {0, I*(-1 + ZA)}},

C[ -F[1] , F[1] ] == {{0, (-I)*mP*(-1 + ZmP*ZP)}, {0, (-I)*mP*(-1 + ZmP*ZP)}, {0, I*(-1 + ZP)}, {0, I*(-1 + ZP)}, {0, 0}, {0, 0}},

C[ -F[1] , F[1] , V[1] ] == {{(-I)*e, (-I)*e*(-1 + Sqrt[ZA]*ZAPP*ZP)}, {(-I)*e, (-I)*e*(-1 + Sqrt[ZA]*ZAPP*ZP)}}

}

