(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Phi34",
  Authors -> {"Raj Patil"},
  Emails -> {"raj.patil.physics@gmail.com"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
S[1] == {
    PropagatorLabel -> "\[Phi]",
    SelfConjugate -> True,
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mP,
    Indices -> {} }
}


(*        Definitions       *)


mP[ ___ ] := mP;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] ] == {{0, (-I)*(-mP^2 + mP^2*ZmP^2*ZP + dv*g3*ZP^2)}, {0, (-I)*(-1 + ZP)}},

C[ S[1] , S[1] , S[1] ] == {{(-I)*g3, (-I)*(-g3 + dv*g4*ZP^(3/2) + g3*Zg3*ZP^(3/2))}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-I)*g4, (-I)*g4*(-1 + Zg4*ZP^2)}},

C[ S[1] ] == {{0, (-I)*dv*mP^2*Sqrt[ZP]}}

}

