(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"ScalarQEDHiggsed",
  Authors -> {"Raj Patil"},
  Institutions -> {""}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={S[2]};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> mA,
    Indices -> {} },

U[1] == {
    SelfConjugate -> False,
    PropagatorLabel -> "c",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> mc,
    Indices -> {} },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> Straight,
    PropagatorArrow -> None,
    Mass -> mH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "b",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mb,
    Indices -> {} }
}


(*        Definitions       *)

FAGaugeXi[ U[1] ] = 1;
FAGaugeXi[ S[1] ] = 1;
FAGaugeXi[ S[2] ] = 1;

mA[ ___ ] := mA;
mc[ ___ ] := mc;
mH[ ___ ] := mH;
mb[ ___ ] := mb;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{((-3*I)/2)*g4, ((-3*I)/2)*g4*(-1 + Zb^2*Zbbbb)}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-1/2*I)*g4, (-1/2*I)*g4*(-1 + Zb*ZbbHH*ZH)}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{((-3*I)/2)*g4, ((-3*I)/2)*g4*(-1 + ZH^2*ZHHHH)}},

C[ S[2] , S[2] , S[1] ] == {{(-1/2*I)*g4*vev, (-1/2*I)*g4*vev*(-1 + Zb*ZbbH*Sqrt[ZH]*Zv)}},

C[ S[1] , S[1] , S[1] ] == {{((-3*I)/2)*g4*vev, ((-3*I)/2)*g4*vev*(-1 + ZH^(3/2)*ZHHH*Zv)}},

C[ S[1] , S[1] ] == {{0, (-1/4*I)*g4*vev^2*(-2 - ZH + ZH*Zv^2 + 2*ZH*ZmH^2*Zv^2)}, {0, (-I)*(-1 + ZH)}},

C[ S[2] , S[2] ] == {{0, (-1/4*I)*vev^2*(-(g4*Zb) + g4*Zb*Zv^2 - 4*e^2*FAGaugeXi[V[1]] + 4*e^2*Zb*Zmb^2*Zv^2*FAGaugeXi[V[1]])}, {0, (-I)*(-1 + Zb)}},

C[ S[1] ] == {{0, (-1/4*I)*g4*vev^3*Sqrt[ZH]*(-1 + Zv)*Zv*(1 + Zv)}},

C[ S[2] , S[2] , V[1] , V[1] ] == {{(2*I)*e^2, (2*I)*e^2*(-1 + ZA*ZAAbb*Zb)}},

C[ S[1] , S[1] , V[1] , V[1] ] == {{(2*I)*e^2, (2*I)*e^2*(-1 + ZA*ZAAHH*ZH)}},

C[ S[1] , V[1] , V[1] ] == {{(2*I)*e^2*vev, (2*I)*e^2*vev*(-1 + ZA*ZAAH*Sqrt[ZH]*Zv)}},

C[ V[1] , V[1] ] == {{0, (-I)*(-1 + ZA)}, {0, I*e^2*vev^2*(-1 + ZA*ZmA^2*Zv^2)}, {0, I*(-1 + ZA)}},

C[ S[2] , S[1] , V[1] ] == {{e, e*(-1 + ZAbH*Sqrt[ZA*Zb*ZH])}, {-e, -(e*(-1 + ZAbH*Sqrt[ZA*Zb*ZH]))}},

C[ -U[1] , U[1] ] == {{0, (-I)*e^2*vev^2*(-1 + Zc*Zmc^2*Zv^2)*FAGaugeXi[V[1]]}, {0, I*(-1 + Zc)}, {0, 0}},

C[ S[1] , -U[1] , U[1] ] == {{(-I)*e^2*vev*FAGaugeXi[V[1]], (-I)*e^2*vev*(-1 + Zc*ZccH*Sqrt[ZH]*Zv)*FAGaugeXi[V[1]]}}

}

M$IntParams = {mA -> e*vev, mb -> e*vev*Sqrt[FAGaugeXi[V[1]]], mc -> e*vev*Sqrt[FAGaugeXi[V[1]]], mH -> (Sqrt[g4]*vev)/Sqrt[2]} ;
